apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest-logger
  template:
    metadata:
      labels:
        app: speedtest-logger
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: speedtest-logger
          image: k8s101registry.azurecr.io/speed-test-logger:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: singleRun
              value: "false"
            - name: speedTestApiUrl
              value: http://speedtest-api-service
            - name: KubeMQ_ServerAddress
              value: kubemq-cluster-node:50000
            - name: KubeMQ_Channel
              value: speedtest
